# Generated by Django 2.0.7 on 2018-11-11 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LimitWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Centro')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('reward_points', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResiduoLugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.IntegerField()),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Centro')),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Residuo')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=None, related_name='userpoints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='punto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.UserProfile'),
        ),
        migrations.AddField(
            model_name='punto',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Residuo'),
        ),
        migrations.AddField(
            model_name='limitwaste',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Residuo'),
        ),
    ]
