# Generated by Django 2.0.7 on 2018-12-03 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_cita_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('articulo', models.CharField(max_length=40)),
                ('antes', models.IntegerField(default=0)),
                ('despues', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
