# Generated by Django 2.0.7 on 2018-10-19 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20180924_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=None, related_name='userpoints', to=settings.AUTH_USER_MODEL),
        ),
    ]
