# Generated by Django 2.0.7 on 2019-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_auto_20190326_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(default='example.jpg', upload_to='static/webpage/images/partners/'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='image',
            field=models.ImageField(upload_to='static/webpage/images/catalogo/'),
        ),
    ]
