# Generated by Django 2.0.7 on 2019-03-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_auto_20190326_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='telefono',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
