# Generated by Django 2.0.7 on 2019-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20190329_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='contacto',
            field=models.CharField(default='No disponible', max_length=50),
        ),
    ]
